### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ChrisMurphy** [bgoodearl/MVC5NgDemo_ADFS#1]
Hi, just been looking through this as a nice example. Noticed that the following files that are referenced in the project "MVC5NgDemo_ADFS" are missing from the git repository:
- rehearsalDataService.js
- rehearsalEdit.html
- rehearsalEdit.js

**Comment by rhurlbut** [comment]
These files were in the other projects but not copied to this one. The project "MVC5NgDemo_ADFS" has been updated.
